### ISSUE TITLE
Update to GNAT Community 2020

### ISSUE THREAD

**Issue by jklmnn** [Componolit/SXML#81]
When compiling SXML with GNAT Community 2020 I get the following error:
```
sxml.adb:66:13: error: not fully conformant with declaration at sxml.ads:320
sxml.adb:66:13: error: predicate of "D" does not match
```

**Comment by jklmnn** [comment]
It seems that the type `Content_Base_Type` and its subtype `Content_Type` need to have the same predicate.

**Comment by senier** [comment]
> It seems that the type `Content_Base_Type` and its subtype `Content_Type` need to have the same predicate.

No, this is an issue in the code that remained undetected in previous compiler versions. While the spec uses `Content_Base_Type`, the implementation uses `Content_Type` which is clearly an error.
